# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: search_post_development
  user: danil
  password: "12345"
  pool: 5
  timeout: 5000